BasketballBackend/Backend/Auth/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('org/',views.org_account, name='org'),
]

BasketballBackend/Backend/Backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('News.urls')),
    path('schedule/', include('Games.urls')),
    path('teams/', include('Teams.urls')),
    path('account/', include('Auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BasketballBackend/Backend/Games/urls.py
from django.urls import path
from . import views

app_name = 'Games'

urlpatterns = [
    path('', views.schedule, name="schedule"),
    path('archieve/', views.archieve, name='archieve'),
]

BasketballBackend/Backend/Teams/urls.py
from django.urls import path
from . import views

app_name = 'Teams'

urlpatterns = [
    path('', views.teams, name='teams'),
    path('<int:team_id>/', views.team_detail, name='team-detail')
]

BasketballBackend/Backend/Teams/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from Auth.models import UserProfile

class Team(models.Model):
    name = models.CharField(verbose_name="Название команды", max_length=120, unique=True)
    

    def __str__(self):
        return self.name

class Player(models.Model):
    team = models.ForeignKey(Team, verbose_name="Команда игрока", on_delete=models.CASCADE)
    name = models.CharField(verbose_name="Имя", max_length=120)
    last_name = models.CharField(verbose_name="Фамилия", max_length=120)
    middle_name = models.CharField(verbose_name="Отчество", blank=True, null=True, max_length=120)
    photo = models.ImageField(verbose_name='Фото игрока', blank=True, upload_to='player_photos/', validators=[FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))])
    user_profile = models.ForeignKey(UserProfile, related_name='players', on_delete=models.SET_NULL, null=True, blank=True)
    height = models.PositiveIntegerField(verbose_name="Рост", blank=True, null=True)

    def __str__(self):
        return f"{self.last_name} {self.name} {self.middle_name or ''}"

    @property
    def get_photo(self):
        if not self.photo:
            return 'media/images/placeholder.png'
        return self.photo.url
    
    @property
    def get_full_name(self):
        return f'{self.last_name} {self.name}'

class TeamStatistic(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    logo = models.ImageField(verbose_name="Логотип команды", upload_to='teams/logos/', blank=True)
    rating = models.IntegerField(verbose_name = "Рейтинг команды", default=0, blank=True)
    played_games = models.IntegerField(verbose_name="Сыграно игр", default=0, blank=True)
    wins = models.IntegerField(verbose_name="Победы", default=0, blank=True)
    draws = models.IntegerField(verbose_name="Ничьи", default=0, blank=True)
    losses = models.IntegerField(verbose_name="Поражения", default=0, blank=True)

    @property
    def get_logo(self):
        if not self.logo:
            return 'media/images/placeholder.png'
        return self.logo.url

    def win_percentage(self):
        if self.played_games == 0:
            return 0
        else:
            return (self.wins + 0.5 * self.draws) / self.played_games * 100

    def __str__(self):
        return f"Статистика команды {self.team.name}"

BasketballBackend/Backend/Teams/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import Team, TeamStatistic
def teams(request):
    teams = Team.objects.all()
    query = request.GET.get('search')
    if query:
        teams = teams.filter(name__icontains=query)
    return render(request, 'teams.html', {'teams': teams, 'query': query})

def team_detail(request, team_id):
    team = get_object_or_404(Team, id=team_id)
    team_statistic = TeamStatistic.objects.get(team=team)
    players = team.player_set.all()
    matches = team.team_1_matches.filter(is_finished=False) | team.team_2_matches.filter(is_finished=False)
    return render(request, 'team-pages/team-page.html', {'team': team, 'statistic': team_statistic, 'players': players, 'matches': matches})

BasketballBackend/Backend/templates/archieve.html
{% extends 'layout.html'%}
{% load static %}
<!--<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href=" {% static 'css/archieve.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>Архив</title>
</head>
<body>
    <div class="flag" id="flag"></div>

    {% include 'login_registration.html' %}

    <header id="header">
        <img src="{% static 'content/images/logo.png' %}" alt="Лого сайта" class="logo" id="logo">
        <div class="navigation">
            <a href="{% url 'index' %}" class="main-link">Главная</a>
            <a href="{% url 'Teams:teams' %}" class="teams-link">Команды</a>
            <a href="{% url 'Games:schedule' %}" class="timetable-link">Расписание</a>
            <a href="{% url 'results' %}" class="results-link">Результаты</a>
            <a href="{% url 'Games:archieve' %} " class="archieve-link">Архив</a>
            <a href="{% url 'contact' %}" class="contacts-link">Контакты</a>
        </div>
        {% if not user.is_authenticated %}
        <div class="buttons">
            <p class="registration-btn" id="registration-button_header">Регистрация</p>
            <p class="logIn-btn" id="logIn-button_header">Войти</p>
        </div>
        {% elif user.is_superuser %}
        <div class="buttons">
            <div class="registration-btn" id="registration-button_header" style="display:none;"></div><div class="logIn-btn" id="logIn-button_header" style="display:none;"></div>
            <p class="registration-btn"><a href="{% url 'org' %}">Управление</a></p>
            <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
        </div>
        {% else %}
        <div class="buttons">
            <div class="registration-btn" id="registration-button_header" style="display:none;"></div><div class="logIn-btn" id="logIn-button_header" style="display:none;"></div>
            <p class="registration-btn">Личный кабинет</a></p>
            <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
        </div>
        {% endif %}
    </header>
-->
    {%block title%}Архив{%endblock title%}
    {%block style%}<link rel="stylesheet" href=" {% static 'css/archieve.css' %}">{%endblock style%}
    {%block content%}
    <main class="main">
        <div class="reglog_backgr"></div>

        <form class="lists">
            <select class="period_list" name="season">
                <option value="">Все сезоны</option>
                <option value="1">Сезон 1</option>
                <option value="2">Сезон 2</option>
            </select>
    
            <select class="match_list" name="match">
                <option value="">Выберите матч</option>
                {% for match in matches %}
                    <option value="{{ match.id }}">{{ match }}</option>
                {% endfor %}
            </select>
    
            <button type="submit">Фильтровать</button>
        </form>
    
        <div class="match_cards">
            {% for match in matches %}
                <div class="match_card">
                    <div class="match_command_1">
                        {% if match.team_1.teamstatistic_set.first.logo %}
                        <img class="match_command_1-photo" src="{{match.team_1.teamstatistic_set.first.get_logo}}">
                        {% else %}
                        <img class="match_command_1-photo" src="{% static 'content/images/noimg.jpg' %}">
                        {% endif %}
                        <p class="match_command_1-name">{{ match.team_1 }}</p>
                    </div>
                    <div class="match_info">
                        <p class="match_date">{{ match.date }}</p>
                        <p class="match_place">{{ match.place }}</p>
                        <p class="match-season">Сезон {{ match.season }}</p>
                        <p class="match_score">{{ match.team_1_goals }}:{{ match.team_2_goals }}</p>
                    </div>
                    <div class="match_command_2">
                        <p class="match_command_2-name">{{ match.team_2 }}</p>
                        {% if match.team_2.teamstatistic_set.first.logo %}
                        <img class="match_command_2-photo" src="{{match.team_2.teamstatistic_set.first.get_logo}}">
                        {% else %}
                        <img class="match_command_2-photo" src="{% static 'content/images/noimg.jpg' %}">
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>

        <p class="scores_title">Статистика</p>
        <div class="scores_form">
            {% for team_stat in team_statistics %}
            <div class="team_statistic">
                <div class="team_info">
                    <p class="team_name">Название команды: {{ team_stat.team }}</p>
                    <p class="team_rating">Рейтинг команды: {{ team_stat.rating }}</p>
                    <p class="team_played_games">Сыграно игр: {{ team_stat.played_games }}</p>
                    <p class="team_wins">Победы команды: {{ team_stat.wins }}</p>
                    <p class="team_draws">Ничьи команды: {{ team_stat.draws }}</p>
                    <p class="team_losses">Проигрыши команды: {{ team_stat.losses }}</p>
                </div>
            </div>
        {% endfor %}
        </div>
    </main>
    <!--<footer>
        <img src="{% static 'content/images/logo.png' %}" alt="Лого сайта" class="logo">
        <div class="links">
            <div class="link-str">
                <a href="https://vk.com/ystu_physedu" target="_blank" class="vk-link"><i class='bx bxl-vk'></i></a>
                <a href=" {% url 'docs' %} " class="doc-link">Документация</a>
                <a href=" {% url 'contact' %} " class="contact-link">Контакты</a>
                <a href="https://www.ystu.ru/" target="_blank" class="site-link">www.ystu.ru</a>
            </div>
            <div class="link-buttons">
                <a href="" class="mail-link">ПОЧТА@YSTU.RU</a>
                <div class="btn-lnk">
                    {% if not user.is_authenticated %}
                        <p class="registration-btn" id="registration-button_footer">Регистрация</p>
                        <p class="logIn-btn" id="logIn-button_footer">Войти</p>
                    {% elif user.is_superuser %}
                        <p class="registration-btn"><a href="{% url 'org' %}">Управление</a></p>
                        <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
                    {% else %}
                        <p class="registration-btn">Личный кабинет</a></p>
                        <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
                    {% endif %}
                </div>
            </div>
        </div> 
    </footer>-->
    {%endblock content%}
    {%block scripts%}<script src="{% static 'scripts/reg.js' %}"></script>{%endblock scripts%}
<!--</body>
</html>-->

BasketballBackend/Backend/templates/contacts.html
{%extends 'layout.html'%}
{% load static %}
<!--<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href=" {% static 'css/contacts.css' %}">
    <link rel="shortcut icon" href=" {% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>Контакты</title>
</head>
<body>
    <div class="flag" id="flag"></div>

    {% include 'login_registration.html' %}

    <header id="header">
        <img src=" {% static 'content/images/logo.png' %}" alt="Лого сайта" class="logo" id="logo">
        <div class="navigation">
            <a href="{% url 'index' %}" class="main-link">Главная</a>
            <a href="{% url 'Teams:teams' %}" class="teams-link">Команды</a>
            <a href="{% url 'Games:schedule' %}" class="timetable-link">Расписание</a>
            <a href="{% url 'results' %}" class="results-link">Результаты</a>
            <a href="{% url 'Games:archieve' %} " class="archieve-link">Архив</a>
            <a href="{% url 'contact' %}" class="contacts-link">Контакты</a>
        </div>
        <div class="buttons">
            {% if not user.is_authenticated %}
            <div class="buttons">
                <p class="registration-btn" id="registration-button_header">Регистрация</p>
                <p class="logIn-btn" id="logIn-button_header">Войти</p>
            </div>
            {% elif user.is_superuser %}
            <div class="buttons">
                <div class="registration-btn" id="registration-button_header" style="display:none;"></div><div class="logIn-btn" id="logIn-button_header" style="display:none;"></div>
                <p class="registration-btn"><a href="{% url 'org' %}">Управление</a></p>
                <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
            </div>
            {% else %}
            <div class="buttons">
                <div class="registration-btn" id="registration-button_header" style="display:none;"></div><div class="logIn-btn" id="logIn-button_header" style="display:none;"></div>
                <p class="registration-btn">Личный кабинет</a></p>
                <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
            </div>
            {% endif %}
        </div>
    </header>-->
    {%block title%}Контакты{%endblock title%}
    {%block style%}<link rel="stylesheet" href=" {% static 'css/contacts.css' %}">{%endblock style%}
    {%block content%}
    <main class="main">
        <div class="reglog_backgr"></div>

        <section class="organizers">
            <p class="tour-org_title">Организаторы</p>
            <div class="pht-org">
                <div class="pht-org_card">
                    <div class="pht-org_photo"></div>
                    <p class="pht-org_signature">
                        Фамилия Имя
                        Должность
                        Контактный телефон
                    </p>
                </div>
                <div class="pht-org_card">
                    <div class="pht-org_photo"></div>
                    <p class="pht-org_signature">
                        Фамилия Имя
                        Должность
                        Контактный телефон
                    </p>
                </div>
                <div class="pht-org_card">
                    <div class="pht-org_photo"></div>
                    <p class="pht-org_signature">
                        Фамилия Имя
                        Должность
                        Контактный телефон
                    </p>
                </div>
                <div class="pht-org_card">
                    <div class="pht-org_photo"></div>
                    <p class="pht-org_signature">
                        Фамилия Имя
                        Должность
                        Контактный телефон
                    </p>
                </div>
            </div>
        </section>

        <section class="partner">
            {% for partner in partners %}
            <p class="tour-pr_title">Партнер</p>
            <div class="pht-pr">
                <div class="pht-pr_card">
                    {% if partner.photo %}
                    <img class="pht-pr_photo" src="{{partner.photo.url}}">
                    {% else %}
                    <img class="pht-pr_photo" src="{% static 'content/images/logoplaceholder.jpg' %}">
                    {% endif %}
                    <p class="pht-pr_signature">
                        {{partner.company_name}}
                        {% if partner.partner_site_link %}
                        {{partner.partner_site_link}}
                        {% endif %}
                    </p>
                </div>
                <p class="pr_card-text">
                    {{partner.partner_description}}
                </p>
            </div>
            {% endfor %}
        </section>
    </main>
    {%endblock content%}
    <!--<footer>
        <img src=" {% static 'content/images/logo.png' %}" alt="Лого сайта" class="logo">
        <div class="links">
            <div class="link-str">
                <a href="https://vk.com/ystu_physedu" target="_blank" class="vk-link"><i class='bx bxl-vk'></i></a>
                <a href=" {% url 'docs' %} " class="doc-link">Документация</a>
                <a href=" {% url 'contact' %} " class="contact-link">Контакты</a>
                <a href="https://www.ystu.ru/" target="_blank" class="site-link">www.ystu.ru</a>
            </div>
            <div class="link-buttons">
                <a href="" class="mail-link">ПОЧТА@YSTU.RU</a>
                <div class="btn-lnk">
                    {% if not user.is_authenticated %}
                        <p class="registration-btn" id="registration-button_footer">Регистрация</p>
                        <p class="logIn-btn" id="logIn-button_footer">Войти</p>
                    {% elif user.is_superuser %}
                    <div class="registration-btn" id="registration-button_footer" style="display:none;"></div><div class="logIn-btn" id="logIn-button_footer" style="display:none;"></div>
                        <p class="registration-btn"><a href="{% url 'org' %}">Управление</a></p>
                        <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
                    {% else %}
                    <div class="registration-btn" id="registration-button_footer" style="display:none;"></div><div class="logIn-btn" id="logIn-button_footer" style="display:none;"></div>
                        <p class="registration-btn">Личный кабинет</a></p>
                        <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </footer>
-->
    {%block scripts%}<script src="{% static 'scripts/reg.js' %}"></script>{%endblock scripts%}
<!--</body>
</html>-->

BasketballBackend/Backend/templates/results.html
{%extends 'layout.html'%}
{% load static %}
<!--<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/results.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>Результаты</title>
</head>
<body>
    <div class="flag" id="flag"></div>

    {% include 'login_registration.html' %}

    <header id="header">
        <img src="{% static 'content/images/logo.png' %}" alt="Лого сайта" class="logo" id="logo">
        <div class="navigation">
            <a href="{% url 'index' %}" class="main-link">Главная</a>
            <a href="{% url 'Teams:teams' %}" class="teams-link">Команды</a>
            <a href="{% url 'Games:schedule' %}" class="timetable-link">Расписание</a>
            <a href="{% url 'results' %}" class="results-link">Результаты</a>
            <a href="{% url 'Games:archieve' %} " class="archieve-link">Архив</a>
            <a href="{% url 'contact' %}" class="contacts-link">Контакты</a>
        </div>
        {% if not user.is_authenticated %}
        <div class="buttons">
            <p class="registration-btn" id="registration-button_header">Регистрация</p>
            <p class="logIn-btn" id="logIn-button_header">Войти</p>
        </div>
        {% elif user.is_superuser %}
        <div class="buttons">
            <div class="registration-btn" id="registration-button_header" style="display:none;"></div><div class="logIn-btn" id="logIn-button_header" style="display:none;"></div>
            <p class="registration-btn"><a href="{% url 'org' %}">Управление</a></p>
            <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
        </div>
        {% else %}
        <div class="buttons">
            <div class="registration-btn" id="registration-button_header" style="display:none;"></div><div class="logIn-btn" id="logIn-button_header" style="display:none;"></div>
            <p class="registration-btn">Личный кабинет</a></p>
            <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
        </div>
        {% endif %}
    </header>
-->
    {%block title%}Результаты{%endblock title%}
    {%block style%}<link rel="stylesheet" href="{% static 'css/results.css' %}">{%endblock style%}
    {%block content%}
    <main class="main">
        <div class="reglog_backgr"></div>

        <form method="GET" class="list">
            <select class="comand_list" name="team" id="tournm_comand" required>
                <option value="">Выберите команду</option>
                {% for team in teams %}
                <option value="{{team.name}}">{{team.name}}</option>
                {% endfor %}
            </select>

            <button type="submit">Фильтровать</button>
        </form>

        {% for match in matches %}
            <p class="match_title">{{match.team_1.name}} vs {{match.team_2.name}}</p>
            <div class="match_card">
                <div class="match_command_1">
                    {% if match.team_1.teamstatistic_set.first.logo %}
                    <img class="match_command_1-photo" src="{{match.team_1.teamstatistic_set.first.get_logo}}">
                    {% else %}
                    <img class="match_command_1-photo" src="{% static 'content/images/noimg.jpg' %}">
                    {% endif %}
                    <p class="match_command_1-name">{{match.team_1.name}}</p>
                </div>
                <div class="match_info">
                    <p class="match_date">{{match.date}} - {{match.time}}</p>
                    <p class="match_place">{{match.place}}</p>
                    <p class="match-season">{{match.season}}</p>
                    <p class="match_score">{{match.team_1_goals}}:{{match.team_2_goals}}</p>
                </div>
                <div class="match_command_2">
                    <p class="match_command_2-name">{{match.team_2.name}}</p>
                    {% if match.team_2.teamstatistic_set.first.logo %}
                    <img class="match_command_2-photo" src="{{match.team_2.teamstatistic_set.first.get_logo}}">
                    {% else %}
                    <img class="match_command_2-photo" src="{% static 'content/images/noimg.jpg' %}">
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </main>
    {%endblock content%}
    <!--
    <footer>
        <img src="{% static 'content/images/logo.png' %}" alt="Лого сайта" class="logo">
        <div class="links">
            <div class="link-str">
                <a href="https://vk.com/ystu_physedu" target="_blank" class="vk-link"><i class='bx bxl-vk'></i></a>
                <a href=" {% url 'docs' %} " class="doc-link">Документация</a>
                <a href=" {% url 'contact' %} " class="contact-link">Контакты</a>
                <a href="https://www.ystu.ru/" target="_blank" class="site-link">www.ystu.ru</a>
            </div>
            <div class="link-buttons">
                <a href="" class="mail-link">ПОЧТА@YSTU.RU</a>
                <div class="btn-lnk">
                    {% if not user.is_authenticated %}
                        <p class="registration-btn" id="registration-button_footer">Регистрация</p>
                        <p class="logIn-btn" id="logIn-button_footer">Войти</p>
                    {% elif user.is_superuser %}
                    <div class="registration-btn" id="registration-button_footer" style="display:none;"></div><div class="logIn-btn" id="logIn-button_footer" style="display:none;"></div>
                        <p class="registration-btn"><a href="{% url 'org' %}">Управление</a></p>
                        <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
                    {% else %}
                    <div class="registration-btn" id="registration-button_footer" style="display:none;"></div><div class="logIn-btn" id="logIn-button_footer" style="display:none;"></div>
                        <p class="registration-btn">Личный кабинет</a></p>
                        <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </footer>
-->
    {%block scripts%}<script src="{% static 'scripts/reg.js' %}"></script>{%endblock scripts%}
<!--</body>
</html>-->

BasketballBackend/Backend/templates/teams.html
{%extends 'layout.html'%}
{% load static %}
{%block title%}Команды{%endblock title%}
{%block style%}<link rel="stylesheet" href="{% static 'css/teams.css' %}">{%endblock style%}
<!--<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/teams.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>Команды</title>
</head>
<body>
    <div class="flag" id="flag"></div>

    {% include 'login_registration.html' %}

    <header id="header">
        <img src="{% static 'content/images/logo.png' %}" alt="Лого сайта" class="logo" id="logo">
        <div class="navigation">
            <a href="{% url 'index' %}" class="main-link">Главная</a>
            <a href="{% url 'Teams:teams' %}" class="teams-link">Команды</a>
            <a href="{% url 'Games:schedule' %}" class="timetable-link">Расписание</a>
            <a href="{% url 'results' %}" class="results-link">Результаты</a>
            <a href="{% url 'Games:archieve' %} " class="archieve-link">Архив</a>
            <a href="{% url 'contact' %}" class="contacts-link">Контакты</a>
        </div>
        {% if not user.is_authenticated %}
        <div class="buttons">
            <p class="registration-btn" id="registration-button_header">Регистрация</p>
            <p class="logIn-btn" id="logIn-button_header">Войти</p>
        </div>
        {% elif user.is_superuser %}
        <div class="buttons">
            <div class="registration-btn" id="registration-button_header" style="display:none;"></div><div class="logIn-btn" id="logIn-button_header" style="display:none;"></div>
            <p class="registration-btn"><a href="{% url 'org' %}">Управление</a></p>
            <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
        </div>
        {% else %}
        <div class="buttons">
            <div class="registration-btn" id="registration-button_header" style="display:none;"></div><div class="logIn-btn" id="logIn-button_header" style="display:none;"></div>
            <p class="registration-btn">Личный кабинет</a></p>
            <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
        </div>
        {% endif %}
    </header>
-->{%block content%}
    <main class="main">
        <div class="reglog_backgr"></div>
    
        <form action="" method="get" class="search_field">
            <input type="search" name="search" placeholder="Введите название команды">
            <button type="submit" class="search_btn">
                <i class='bx bx-search'></i>
            </button>
        </form>
    
        <section class="comand_list">
            {% for team in teams %}
            <div class="comand_card">
                {% if team.teamstatistic_set.first.logo %}
                <img class="comand_card-photo" src="{{ team.teamstatistic_set.first.get_logo }}">
                {% else %}
                <img class="comand_card-photo" src="{% static 'content/images/noimg.jpg' %}">
                {% endif %}
                <p class="comand_card-name">{{ team.name }}</p>
                <a href="{% url 'Teams:team-detail' team.id %}" class="comand_card-link">❯</a>
            </div>
            {% empty %}
            <h2>Команды не найдены</h2>
            {% endfor %}
        </section>
{%endblock content%}
    <!--<footer>
        <img src="{% static 'content/images/logo.png' %}" alt="Лого сайта" class="logo">
        <div class="links">
            <div class="link-str">
                <a href="https://vk.com/ystu_physedu" target="_blank" class="vk-link"><i class='bx bxl-vk'></i></a>
                <a href=" {% url 'docs' %} " class="doc-link">Документация</a>
                <a href=" {% url 'contact' %} " class="contact-link">Контакты</a>
                <a href="https://www.ystu.ru/" target="_blank" class="site-link">www.ystu.ru</a>
            </div>
            <div class="link-buttons">
                <a href="" class="mail-link">ПОЧТА@YSTU.RU</a>
                <div class="btn-lnk">
                    {% if not user.is_authenticated %}
                        <p class="registration-btn" id="registration-button_footer">Регистрация</p>
                        <p class="logIn-btn" id="logIn-button_footer">Войти</p>
                    {% elif user.is_superuser %}
                        <div class="registration-btn" id="registration-button_footer" style="display:none;"></div><div class="logIn-btn" id="logIn-button_footer" style="display:none;"></div>
                        <p class="registration-btn"><a href="{% url 'org' %}">Управление</a></p>
                        <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
                    {% else %}
                        <div class="registration-btn" id="registration-button_footer" style="display:none;"></div><div class="logIn-btn" id="logIn-button_footer" style="display:none;"></div>
                        <p class="registration-btn">Личный кабинет</a></p>
                        <p class="logIn-btn"><a href="{% url 'logout' %}">Выйти</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </footer>
-->
    {%block scripts%}<script src="{% static 'scripts/reg.js' %}"></script>{%endblock scripts%}
<!--</body>
</html>-->